# Directory Settings
source: ./src
destination: ./build
plugins_dir: ./src/_plugins

# Site settings
title: Chinternet - I LEARN YOU CODE. Coding tutorials, memes, cute cats, games.
email: chinternet@alexchin.co.uk
description: > # Chin + Internet = Chinternet. Learn how to code. Discover fun memes! #lol - Chinternet.lol
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chinternet.lol" # the base hostname & protocol for your site

sitemap:
  # local: false
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Build settings
markdown: kramdown

include: ['.nojekyll']
exclude: ['bower_components', 'node_modules', 'package.json', 'bower.json', 'config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'assets']
# keep_files: ['build/css']
